tool/cstar_perf/tool/stress_compare.py

A number of my new regression profiles (see [this branch](https://github.com/mambocab/cstar_perf/tree/regression-tests)) failed with the error `Nodetool operation missing nodes list` (see [here](https://gist.github.com/mambocab/1d735689f19596596061) for links).
This goes against [the documentation for the `nodetool` operation](http://datastax.github.io/cstar_perf/running_tests.html#type-nodetool), which says that it should run on all nodes if `nodes` is not specified. I like the sound of that, so this PR just removes the check for `nodes`, and sets `nodes` to `all` if `nodes` isn't specified.

run nodetool on all nodes if no 'nodes' argument

---

tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/stress_compare.py

This supports creating data with one job and then using that same data on a subsequent job.
Example write:
```
{
"revisions":[
{"revision":"cassandra-2.1.4", "leave_data":true, "cluster_name": "Test_9619"}
],
"title":"#9619 perf regression - just write with leave_data=True",
"log":"stats.9619.write.json",
"operations": [
{"type":"stress","command":"write n=1M -rate threads=300 -col n=FIXED\\(50\\)",
"wait_for_compaction":false}
]
}
```
Example read:
```
{
"initial_destroy": false,   
"revisions":[
{"revision":"cassandra-2.1.4", "leave_data":true, "cluster_name": "Test_9619"},
{"revision":"cassandra-2.1.5", "leave_data":true, "cluster_name": "Test_9619"},
{"revision":"cassandra-2.1.6", "leave_data":true, "cluster_name": "Test_9619"}     
],
"title":"#9619 perf regression - just read after …
```

Leave data benchmark

---

tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_cassandra.py

Allows for installing different C* versions on different hosts. I've been running `cstar_perf_stress` with the following file as input to confirm that it works:
https://gist.githubusercontent.com/mambocab/14fd5367ccd46eacc006/raw/745306fc4a1fdba7dccdec2ebd339592c54faaae/revision_overrides.json
You can look at the `output` section in the `nodetool` report for resulting stats file to confirm that the different nodes are running different versions of C*.
As far as I could tell, the return value from the changed `bootstrap` function isn't used anywhere, so I don't think changing the return type will break anything.

adds revision_override option

---

frontend/cstar_perf/frontend/server/model.py
frontend/cstar_perf/frontend/static/js/schedule.js
frontend/cstar_perf/frontend/static/js/util.js
tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/bootstrap.py
tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_deploy.py
tool/cstar_perf/tool/fab_dse.py
tool/cstar_perf/tool/stress_compare.py
tool/cstar_perf/tool/util.py
tool/setup.py

This is an extension @aboudreault's DSE changes from #45 pulled into the cstar_perf repo along with some of my own changes.
Alan's original notes:
Add the DSE support to cstar_perf_tool.  Currently supported:
* Download the DSE binaries from the url config (dse-REVISION-bin.tar.gz)
* Cache DSE binaries on the *cstar_perf_tool server* (download only once, since DSE is ~500mb) 
* Setup DSE binaries in ~/fab
* Start Cassandra using bin/dse utility (DseDamon)
* Ensure things are started and running
* Product selection in the frontend (Cassandra or DSE)
* cstar_perf_stress should then work as normal
Misc Additions
* fab_common.py is now the main fabric tasks file. Based on the choosed product, it calls the proper functions from fab_cassandra.py or fab_dse.py
* JNA can now be downloaded from …

DSE Support

---

tool/cstar_perf/tool/stress_compare.py

I haven't dug into this very far in case there's a different problem or an environment error, but: my regression jobs on cstar.datastax.com are failing with a key error when `stress_compare` looks for a `product` key in a config dictionary. I believe that config dictionary is derived from `cluster_config.json`, so this may be an environment error. If having jobs fail when this isn't present in the config isn't what we want, this change should effectively set the default product to `cstar`.

allow no product key in cluster config

---

tool/cstar_perf/tool/fab_common.py

I've had a couple jobs fail from unicode decoding errors -- see the end of this console trace:
http://cstar.datastax.com/tests/artifacts/8af9ae48-7e79-11e5-8e7a-0256e416528f/console
I think this should work around the issue, though I don't have a local environment to test on.

moves string comparison into try block

---

tool/cstar_perf/tool/fab_dse.py

Without specifying `DSE_HOME`, all DSE commands will fail. Tested with DSE 4.8.1

Specify DSE_HOME when using dse commands

---

setup_cstar_perf_tool.html

Here's how the diff looks in the documentation:

Provide example of how to use cstar_perf_bootstrap with a DSE version. Also specify -v flag when using cstar_perf_bootstrap

---

frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/migrations/0002.cql
frontend/cstar_perf/frontend/server/controllers.py
frontend/cstar_perf/frontend/server/model.py
frontend/cstar_perf/frontend/server/templates/flamegraph.jinja2.html
frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/server/tests/test_model.py
frontend/cstar_perf/frontend/static/graph/js/graph.js
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_flamegraph.py
tool/cstar_perf/tool/stress_compare.py

Here's the PR so we can begin to review. 
1. Install system dependencies
```
sudo apt-get install cmake dtach linux-tools-`uname -r`
```
2. Ensure your kernel has performance profling support:
```
$ sudo perf record -F 99 -g -p <a_running_process_pid> -- sleep 10
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.098 MB perf.data (~4278 samples) ]
```
3. Add NOPASSWD sudo configuration for the cstar user:
``` 
echo "cstar ALL = (root) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/perf
```
4. Enable flamegraph feature in your cluster configuration:
```
"flamegraph": true,
"flamegraph_directory": "/mnt/data/cstar_perf/flamegraph"
```
The flamegraph working directory default to /tmp/flamegraph if not specified. 
5. Migrate the cstar_perf DB using the following …

Initial flamegraph implementation

---

frontend/cstar_perf/frontend/lib/server.py
frontend/cstar_perf/frontend/lib/util.py
frontend/cstar_perf/frontend/server/app.py
frontend/cstar_perf/frontend/server/util.py

This allows specifying username / password in case C* is configured with password authentication in `server.conf`. It also allows to use a specific keyspace. In our case, we had `cassandra_hosts` point to a cluster with enabled password authentication.
````
[server]
cassandra_hosts=10.200.189.13,10.200.189.130,10.200.189.133
cassandra_user=<user>
cassandra_password=<password>
cassandra_keyspace=<keyspace>
```

server.conf allows specifying cassandra username/password and keyspace to be used

---

frontend/cstar_perf/frontend/static/js/schedule.js

Selecting `dse` as the product on the first revision would show the `dse.yaml` div container for that revision. Now when you add a new revision, the `dse.yaml` div container for the previous revision would be hidden, because we don't hide by the div container's id, but just by its css class.
This PR fixes it and correctly uses the `dse.yaml` div container id

Use div id when hiding dse.yaml div container

---

frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/fab_dse.py

This PR will add support to specifying the DSE node type (http://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/startStop/refDseStandalone.html) when running tests against DSE.

Allow specifying the DSE node type

---

tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/fab_deploy.py
tool/cstar_perf/tool/fab_dse.py

This PR allows us to run a perf test where we can install DSE from a branch. 
* All sensitive information (artifactory username / password / url and an oauth token for checking out the DSE branch) will be provided through `cluster_config.json`.
* The user enters `bdp/DSP-1234` in the revision field of the UI. Due to the prefix `bdp/` in the revision field, we know that the user wants to build from a branch. 
* We extract the branch name `DSP-1234` from that revision field and then use it to checkout this particular branch.
* Depending on the DSE version, we either need to run a legacy ant build or a gradle build.  
* The source build will create a tarball from the specified branch and will be running on the node that is hosting `cstar_perf.tool`. Once the tarball got created, it will be …

Allow installing DSE from a source branch

---

frontend/cstar_perf/frontend/static/js/schedule.js

I improved the handling of the `spark-cassandra-stress` dropdown value. The initial approach of adding that value (by doing `$(e).append($("<option value='spark_cassandra_stress'>spark-cassandra-stress</option>"))`) in case `dse` is selected in the product list lead to a couple of issues, where e.g. the `spark-cassandra-stress` option wasn't automatically added when the job was cloned or when a new operation was added.
I created a separate function that deals with the `spark-cassandra-stress` dropdown value. The logic is basically as following:
* in case **only a single** revision has `cassandra` and not `dse` selected, we hide the `spark-cassandra-stress` dropdown value in **all** operations dropdown containers
* we show the `spark-cassandra-stress` dropdown value only when **all** …

Improve handling of spark-cassandra-stress dropdown value

---

tool/cstar_perf/tool/fab_dse.py

The problem is that `~/fab/dse_builds/dse-{revision}` is never cleaned up and so if a a build of the same revision is triggered (but the revision contains updated files), we end up potentially with multiple cassandra jar files in `~/fab/dse_builds/dse-{revision}/resources/cassandra/lib`. The easiest way is to just remove `~/fab/dse_builds/dse-{revision}` before the run, since a couple of codelines later, the tarball will be extracted anyway
@aboudreault can you review please?

Remove previous DSE build folder for a specific version in case it already exists

---

tool/cstar_perf/tool/benchmark.py

The problem with the existing approach of how to run `cqlsh` is that `cqlsh` would be executed itself on the **node hosting the cstar_perf backend** and just provide an IP parameter for connecting to nodeX. 
This would cause problems if the C* version installed on the **cstar_perf backend node** would be much older than on the perf test nodes and you might end up running into an error such as the following:
````
"output": [
"Connection error: ('Unable to connect to any servers', {'10.200.162.76': ProtocolError(\"cql_version '3.2.1' is not supported by remote (w/ native protocol). Supported versions: [u'3.4.0']\",)})", 
""
], 
"revision": "5.0.0", 
"start_date": "2016-01-18T12:08:08.704220", 
"test": "1_cqlsh", 
"type": "cqlsh"
```
In my example I was running DSE 4.8.x (C* 2.1) on the …

SSH onto node before executing cqlsh commands

---

tool/cstar_perf/tool/fab_common.py

This will deal with cleaning up `hints_directory` if it's being set
@aboudreault can you review please?

Deal with hints_directory during cleanup/destroy

---

tool/cstar_perf/tool/fab_common.py

Previously, it would just bind to the hostname and you couldn't establish a remote JMX connection if you don't have the proper name resolution configured. The easy fix is to always bind the RMI server to the host's public IP address.
@aboudreault / @EnigmaCurry can you guys review please?

Bind RMI server to public IP instead of hostname

---

tool/cstar_perf/docker/cstar_docker.py

Returned labels can be null for any container, in which case the script
would abort with an exception.

Prevent exception in case of absent container labels

---

frontend/cstar_perf/frontend/lib/screenshot.py

These pages are the reference for this runtime addition:
https://github.com/SeleniumHQ/docker-selenium#running-the-images
https://bugs.chromium.org/p/chromium/issues/detail?id=519952

Use host mount of /dev/shm to avoid chrome crash

---

frontend/cstar_perf/frontend/lib/server.py
frontend/cstar_perf/frontend/server/app.py
frontend/cstar_perf/frontend/server/model.py

I don't know if it's related to the new C* python driver that got released yesterday (3.3.0), but as of today, I had problems successfully running the cstar_perf UI in a docker container.
I have been seeing that a client would run into a timeout when establishing a connection with C*:
````
WARNING:cassandra.cluster:[control connection] Error connecting to 127.0.0.1:
Traceback (most recent call last):
File "cassandra/cluster.py", line 2154, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37797)
return self._try_connect(host)
File "cassandra/cluster.py", line 2176, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:38315)
connection = self._cluster.connection_factory(host.address, is_control_connection=True)
File "cassandra/cluster.py", …
```

Increase connection timeout when using C* python driver

---

tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_deploy.py

This is for [CASSANDRA-8844](https://issues.apache.org/jira/browse/CASSANDRA-8844). We handle the **cdc** directories the same way as we do the **commitlog_directory** (e.g. not allowed to set them through the cstar_perf UI).
In case the **cdc** directories change with newer [CASSANDRA-8844](https://issues.apache.org/jira/browse/CASSANDRA-8844), we can easily reflect it in this PR.

Allow setting cdc directories through cluster_config.json

---

tool/cstar_perf/docker/cstar_docker.py

This will show the real error happening when running cstar_perf inside a docker container
````
$ cstar_docker launch test_cluster 1 -m
INFO:cstar_docker:Launching a 2 node cluster with a separate client node ...
DEBUG:cstar_docker:docker run --ulimit memlock=100000000:100000000 --privileged --label cstar_node=true --label cluster_name=test_cluster --label cluster_type=cluster --label node=0  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/bin/docker -d -m 2G --name=test_cluster_00  -h test_cluster_00 -v /home/automaton/git/cstar_perf:/home/cstar/git/cstar_perf datastax/cstar_docker
docker: invalid hostname format for --hostname: test_cluster_00.
See 'docker run --help'.
docker: "inspect" requires a minimum of 1 argument.
See 'docker inspect --help'.
Usage:	docker inspect …
```

Dont pipe stderr in order to show real error

---

frontend/cstar_perf/frontend/client/client.py

This should have gone into #196, but it was merged too fast :) 
The PR will fix
````
$ cstar_docker associate test-frontend test-cluster
[172.17.0.2] Executing task 'get_frontend_credentials'
[172.17.0.2] run: cat ~/credentials.txt
[172.17.0.2] out: New server keys saved to /home/cstar/.cstar_perf/server.conf
[172.17.0.2] out: Server public key: zqGjwm9TqaGSPIZ9fysJ+1zvEk0wYPbvndy3RHBZaAt0EjJykEUT66rb0ha4VsUz
[172.17.0.2] out: Server verify code: YWVjYzQzMGUtMTFmMy0xMWU2LWJjMjQtMDI0MmFjMTEwMDAyfFlwdGhXUU9LZGJ0NWpqY294VDc1K21LZGZ5dkRoeW02d2ZrRllBWCtLWE4yTjlWODc3WU9UMGlvOTNJQ2FGNGg=
[172.17.0.2] out:
[172.17.0.3] Executing task 'generate_client_credentials'
[172.17.0.3] put: /Users/nastra/Development/cstar_perf/env/lib/python2.7/site-packages/pexpect/__init__.py -> /tmp/__init__.py …
```

Allow '-' in cluster names

---

frontend/cstar_perf/frontend/client/client.py

If a user specified a wrong revision, the **last_log** field in wasn't set in **stats.revId.json** and therefore this piece of code would fail not and copy back the stats/logs files

CSTAR-143: Do not fail stats/logs gathering in case of a wrong revision

---

tool/cstar_perf/docker/cstar_docker.py

With the latest C* python driver version **3.3.0** I noticed some problems with cstar_perf, where the node would constantly be marked as down. I think for now we should stick with the driver version that works, which is **3.2.2**

Temporarily use C* python driver 3.2.2

---

frontend/cstar_perf/frontend/static/graph/js/graph.js
regression_suites/cstar_perf_regression_monitor.py
tool/cstar_perf/tool/benchmark.py

Since https://issues.apache.org/jira/browse/CASSANDRA-11352 changed how the stress summary table is shown, new test runs all show **undefined** in the graph. The solution to this problem, which is also backward compatible, is quite simple:
- For new test runs, store stress summary entries all with **lowercase** names in **benchmark.py**
- For test runs that are already stored in the DB with **mixed case** names in the summary table, we do a workaround in the **UI** of creating a dict entry with a **lowercase** key. The below picture shows that in the UI, the data object will now have dict keys, where the key has **mixed case** and **lowercase**. If they dict key was already all **lowercase**, we don't modify the dict.
@mshuler can you maybe also push your fix for …

CSTAR-539: Fix stress graph for new format

---

frontend/cstar_perf/frontend/client/api_client.py
frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/server/controllers.py
frontend/cstar_perf/frontend/static/js/view_test.js
tool/cstar_perf/tool/stress_compare.py

Previously, API calls to **/api/tests/status/id/<id>** or **/api/tests/progress/id** would be failing with a **401 - Unauthorized**, because the API user **test-cluster** wouldn't be in the **users** table and also wouldn't have a **role** assigned.
This shows that the API user **test-cluster** by default is not in the **users** table. Also I could not find any documentation for that requirement.
````
select * from cstar_perf.users;
user_id           | full_name       | roles
-------------------+-----------------+-------------------
user@example.com |  User Full Name |          {'user'}
admin@example.com | Admin Full Name | {'admin', 'user'}
(2 rows)
cqlsh> select * from cstar_perf.api_pubkeys ;
name         | pubkey                                                           | user_type …
```

CSTAR-85: Improve JobCancellationTracker / Gracefully handle termination in stress_compare

---

frontend/cstar_perf/frontend/client/client.py
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/stress_compare.py

This PR will now copy/report back the startup log (**nohup.out**) of the Cassandra node. That way it's possible to check e.g. why the JVM startup failed.
The below picture is from a **successful** JVM startup + test run. Both test revisions contain now the startup log:
The below picture is from a **non-successful** run. It shows that the first revision was running fine, but the second revision failed **due to invalid JVM settings**. Therefore in the second revision we only have the startup log:

CSTAR-553: report back Cassandra startup log

---

frontend/supervisord.conf
supervisord.conf

The reason why we want to have fixed names instead of the generated log file names (**/tmp/cstar_perf_X-\<someRandomValue\>**), is that once a cstar_perf component is restarted, the log file with the generated name will be overwritten and lost. However, after a restart we would like to be able to still preserve the log file.

Use fixed names for cstar_perf component logs.

---

tool/cstar_perf/tool/fab_common.py

**system.log** will now contain only log levels **INFO** and upper and we'll have an additional **debug.log** that will contain everything.
The existing **copy-all-logs-code** will already pick up the new **debug.log**

CSTAR-590: Adjust logback config to log DEBUG stuff into debug.log

---

tool/cstar_perf/tool/fab_common.py

The first of these 2 commits fixes a couple bugs:
- The changes to `JVM_EXTRA_OPTS` for `use_jna` would be ignored if the user changed `JVM_EXTRA_OPTS` in their passed-in environment script.
- In the flamegraph-enabling code, the line being added to the environment script isn't terminated.
The second commit makes the changes requested in #227. @tjake, could you please review?
@nastra and/or @mshuler, could you please review all the other changes? Thanks.

Fix gc stat collection

---

tool/cstar_perf/docker/cstar_docker.py

DSE startup might fail due to permission issues when creating the hints directory at the default location (/var/lib/cassandra/hints), therefore we specify **hints_directory** for Docker in the **cluster_config.json** file.
@mambocab @mshuler can you review please?

Define hints_directory in cluster_config for docker

---

tool/cstar_perf/tool/fab_common.py

A leftover from https://github.com/datastax/cstar_perf/pull/238
Specifying any settings in the **dse.yaml** field would fail with
````
[node1] put: <file obj> -> $HOME/fab/dse/resources/dse/conf/dse.yaml
Fatal error: put() encountered an exception while uploading '<StringIO.StringIO instance at 0x7ff468ddffc8>'
Underlying exception:
No such file
````
because **$HOST** needs to be replaced

Fix issue when specifying dse.yaml settings
