datastax/cstar_perf

tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/stress_compare.py
tool/setup.py

@mambocab and @EnigmaCurry review

Add stress_revision support

---

tool/cstar_perf/tool/fab_cassandra.py

Add DENIED_CSTAR_CONFIG

---

frontend/cstar_perf/frontend/server/model.py

support for OrderedMap

---

tool/cstar_perf/tool/fab_cassandra.py

Support to specify more git remotes, easily. 
* Add additional remotes in ~/.cstar_perf/git_remotes.json
```json
{
"alan": "git://github.com/aboudreault/cassandra.git",
...
}
```
* All remote added in git_remotes.json are automatically added and updated.
* If a remote is deleted from the git_remotes.json file, it is automatically removed from the repository remotes.
//cc @EnigmaCurry

Add dynamic git remotes support

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/stress_compare.py

My IDE snuck in some whitespace changes. I can move those to a separate commit, if you prefer.

Use a more readable stress opcount syntax

---

tool/cstar_perf/tool/fab_cassandra.py

Add jeffjirsa remote

---

_sources/index.txt
_sources/running_tests.txt
_sources/setup_cstar_perf_tool.txt

Add some docs about DSE support

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/stress_compare.py

So, the stress setup is now automatically done.
@EnigmaCurry 
fixes #87

Add automatic default stress setup

---

tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/stress_compare.py

Ensure cassandra git has been updated for stress_revision

---

tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_dse.py
tool/cstar_perf/tool/stress_compare.py

- fixes issue with leaving data for subsequent runs
- changes ensure_running() to use nodetool status
- added nodetool drain to destroy() if leave_data=true
- changes wait_for_compaction to run nodetool commands local to each node
- removed superfluous whitespace (let me know if this should be moved to another PR)

persistent data and mixed version fixes

---

frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/lib/screenshot.py
frontend/cstar_perf/frontend/lib/stupid_cache.py
frontend/cstar_perf/frontend/lib/util.py
frontend/cstar_perf/frontend/server/controllers.py
frontend/cstar_perf/frontend/server/model.py
frontend/cstar_perf/frontend/server/templates/schedule.jinja2.html
frontend/cstar_perf/frontend/static/graph/js/graph.js
frontend/cstar_perf/frontend/static/js/schedule.js
frontend/requirements.txt
tool/cstar_perf/tool/fab_deploy.py

This is a rebased version of @aweisberg's #79 pulled into tree.

Add support for associating jobs with a series and graphing the results

---

frontend/cstar_perf/frontend/static/js/schedule.js

very minor fix to get stress_revision taken into account in the UI

---

tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/stress_compare.py

- added libjpeg-dev to docker install to satisfy pillow dependency (http://pillow.readthedocs.org/en/3.0.x/installation.html#external-libraries)
Fixes #53

- wrapped operation iteration block in try/finally to ensure logs are captured

---

frontend/cstar_perf/frontend/server/controllers.py

@mambocab This is for #106. 
The filtering is quite precise. I'll let you decide if it is OK or not.

Add /api/tests endpoint

---

tool/cstar_perf/tool/fab_common.py

what to do about failure to run a command should be up to the caller -- shouldn't kill the system

changed multinode tool command to not break the test on non-zero return

---

source/setup_cstar_perf_tool.rst

Provide example of how to use cstar_perf_bootstrap with a DSE version. Also specify -v flag when using cstar_perf_bootstrap

---

tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_flamegraph.py
tool/cstar_perf/tool/scripts/flamegraph.py
tool/cstar_perf/tool/scripts/utils.py

@EnigmaCurry  still testing, but this is mostly how will it works for now

Remote python execution

---

frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/lib/screenshot.py
frontend/cstar_perf/frontend/server/controllers.py
tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/benchmark.py

Merged version of PR #119 to resolve conflicts and to bring into this repository.

Fix several issues using selenium from docker as well as an issue rendering revisions by of revision by revision label

---

frontend/cstar_perf/frontend/client/api_client.py
frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/lib/util.py
frontend/cstar_perf/frontend/migrations/0003.cql
frontend/cstar_perf/frontend/migrations/0004.cql
frontend/cstar_perf/frontend/server/cluster_api.py
frontend/cstar_perf/frontend/server/controllers.py
frontend/cstar_perf/frontend/server/model.py
frontend/cstar_perf/frontend/server/templates/cluster.jinja2.html
frontend/cstar_perf/frontend/server/templates/test_macro.jinja2.html
frontend/cstar_perf/frontend/server/templates/tests.jinja2.html
frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/static/js/console.js
frontend/requirements.txt

@EnigmaCurry @aboudreault 
This one is a biggie.  It's the merger of 2 branches + some flamegraph for good measure.
See branches before looking here:
https://github.com/datastax/cstar_perf/tree/progress_msg
https://github.com/datastax/cstar_perf/tree/chunked_artifact_storage
- There are 2 migrations that need to occur with this being merged
- A new python dependency on [watchdog](http://pythonhosted.org/watchdog/) has been added
- old test artifacts are still viewable
- a fresh test with chunked artifacts are available
- progress message appears on task list page, task detail, and top of console log page

Chunked artifact storage rebased

---

frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_dse.py
tool/cstar_perf/tool/fab_flamegraph.py

This PR will add support for configuring `dse.yaml` settings. The `dse.yaml` div container in the UI will also only be shown if `dse` is selected from the product dropdown.

Add support for dse.yaml settings

---

frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/static/js/view_test.js

@aboudreault 
Added check for progress message in page refresh logic

added page refresh on test page on progress message changes

---

frontend/cstar_perf/frontend/server/controllers.py

This is inefficient but fixes the problem.  Going to open ticket in backlog to include the status of the test in the series table to make this a single query

added check for completed status on series summary endpoint

---

frontend/cstar_perf/frontend/client/client.py
frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/bootstrap.py
tool/cstar_perf/tool/fab_common.py
tool/cstar_perf/tool/fab_profiler.py
tool/cstar_perf/tool/scripts/utils.py
tool/cstar_perf/tool/stress_compare.py

@nutbunnies Can you give this a quick review?

Implemented yourkit profiling support

---

frontend/cstar_perf/frontend/server/templates/view_test.jinja2.html
frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/docker/cstar_docker.py
tool/cstar_perf/tool/fab_deploy.py
tool/cstar_perf/tool/fab_dse.py

The UI will have a new field where a user can specify Spark Environment settings, which then will be **appended** to `$DSE_HOME/resources/spark/conf/spark-env.sh`. The Spark environment div container will only be visible if `dse` is selected as a product.
This PR contains the 3 commits from https://github.com/datastax/cstar_perf/pull/147. Once https://github.com/datastax/cstar_perf/pull/147 is merged, I will rebase this one here and it should then contain only commit https://github.com/datastax/cstar_perf/commit/27172ecda3dbbdc841165f42199d00bdac36e1c7

Allow spark environment configuration

---

tool/cstar_perf/tool/stress_compare.py

@EnigmaCurry or @aboudreault can you guys please review?

Show executed command for cqlsh and bash in stats file

---

frontend/cstar_perf/frontend/static/js/schedule.js

JVM options were being duplicated as the box was filling twice. This stops that.

Fix jvm select

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/stress_compare.py

This PR will add support for running `spark-cassandra-stress` if `dse` is selected in the product dropdown.
For `spark-cassandra-stress`, the user needs to specify **one** particular node. On this node we will then download / build / execute `spark-cassandra-stress`.

Add support for spark-cassandra-stress

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/command.py
tool/cstar_perf/tool/stress_compare.py

Metrics has to be uploaded on a graphite server when using with cstar_perf
Still need the documentation to do

basic ctool command to be able to setup ctool metrics

---

tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py

This needs to be moved to fab_common, otherwise it won't be removed when running with DSE.

Move 'log' removal to common module.

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/benchmark.py
tool/cstar_perf/tool/stress_compare.py

This PR will add support for running the operations `dse` and `dsetool`. Those two operations will only be visible if **dse** is selected as a product.
For the `dse` command the user can select **one** node as the execution node. The `dsetool` command on the other hand can run on **N** nodes where **1 <= N <= cluster_nodes**.

Add dse / dsetool operations

---

frontend/cstar_perf/frontend/server/model.py
frontend/cstar_perf/frontend/static/graph/js/graph.js

@nastra how do you feel about these minor changes I found running on the production cstar.datastax.com frontend server? When I pulled in the latest PRs, I found these manual edits and would like to get square with master.

Add uncommitted diff found on production cstar.ds.c frontend

---

regression_suites/daily_regression_suites.py
regression_suites/regression_suites.py
regression_suites/util.py

make rolling version tests cover new versions, and remove versions not needed, along with some code cleanup to make things more maintainable.

Perf regression vers cleanup/update

---

regression_suites/cstar_perf_regression_monitor.py
regression_suites/daily_regression_suites.py

@mambocab and @knifewine to review. I'm running the fixed suites now. The regression_monitor job definitely works now.

Regression fix

---

tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py

Ok, take 2. @mshuler Can I get a sanity check, please? And if this needs to be deployed, can you merge and deploy next you're able? I think the pull executes on the stressor node, so I think this needs to be properly deployed.

add josh-mckenzie user to fab_{cassandra,common}

---

tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py

Self-explanatory. @mshuler could you please review, merge, and deploy when you're able?

add sbtourist to repo whitelist

---

frontend/cstar_perf/frontend/static/js/schedule.js
tool/cstar_perf/tool/fab_common.py

For each revision a user can now select if **debug logging** should be enabled or not. If **debug loggin** is enabled, a separate **debug.log** will be created + captured with all the other artifacts.

Users can now set in the UI if debug logging should be enabled

---

frontend/cstar_perf/frontend/server/model.py

Proposed by @nastra. @nastra and @mshuler could you please review?

object_size hack

---

tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py

Adds our good buddy @thobbs to our repo whitelist. @mshuler could you please sanity-check and deploy this?

add @thobbs to whitelist

---

tool/cstar_perf/tool/fab_cassandra.py
tool/cstar_perf/tool/fab_common.py

Hi,
I need to try some performance experiments on cstar.
Would you add my repo to whitelist?
Thanks!

Add yukim's cassandra repo

---

frontend/cstar_perf/frontend/server/model.py

With **cassandra-driver==3.7.0**  we don't run into `if "Keyspace '{ks}' does not exist".format(ks=self.keyspace) in e.message:` anymore when connecting to the cluster, therefore we need to create the keyspace before that & also need to check the cluster if we can skip keyspace creation

Improve detection if keyspace already exists
